### ISSUE TITLE
IServiceNode vs IServiceProvider

### ISSUE THREAD

**Issue by fubar-coder** [JohnMasen/ChakraCore.NET#1]
Hi,

this project looks really promising 👍 .

After skimming over your source code, I noticed that you created your own implementation of something that might be covered by existing dependency injection libraries. Just curious, what was the reason for this decision? Did you try to reduce dependencies?

You could probably still use the IServiceProvider interface, which is available in .NET Frameworks `mscorlib`, as this would allow (in a later step) the usage of other DI frameworks.

EDIT: It seems that you implemented both scopes and multiple implementations of a given service. Maybe a lightweight choice would be using [`Microsoft.Extensions.DependencyInjection`](https://github.com/aspnet/DependencyInjection)?

**Comment by JohnMasen** [comment]
Hi,
The ServiceNode is a bit different to the classic DI. It uses a service container tree instead of a provider table. Here's some key features designed in ServiceNode system, I will write a detailed article to describe the ServiceNode system later. 
1. When a service is not registered in current ServiceNode, lookup in parent node.  
    this makes the service "location aware", by calling service from different node, you will get different behavior.
## Sample:
```

Runtime Node
   +- Context Node
         +- GlobalObject Node   <-- call begins here
   +-Context Node
         +-GlobalObject Node
1. Call Read/Write value at GlobalObject node
2. GlobalObject get IJSValueConvert service and set it's currentNode to GlobalObject Node
3. IJSValueConvert service get IContextSwitch service from currentNode, by searching up, it can always have the correct context switch
```
2.  Each node maintain a stack instead of a table of service instances, this allows user code can temporary "push" a new service to change the system behavior.
 example: IServiceA will call IServiceB at run time, by push a new IServiceB before calling IServiceA function then pop it out after call, you can temporary modify IServiceA behavior without change core code as the new IServiceB code resides in your own project. You can even push a new ServiceC instance ,and by calling it's Begin,End method, let it changes the IServiceB for you. You can find this trick in the Promise implementation.

3. Chaining ServiceNode requires call the Chain at parent object. You can create a DebugNode which wraps a real serviceNode instance in it self. the Chain call to the debug node will spawn a new DebugNode with a new serviceNode inside. this allows you modify the whole service system without change the core code.

**Comment by JohnMasen** [comment]
one more thing: the ChakraCore.NET project contains only 2 classes, what they do is call native API to setup environment and inject necessary services.
user can copy these two classes to their project and modify the injected service instance. This allows library creator easily create their own implementation without modify the core code. Can be useful if someone want to create a Dotnet_Node.js :)
