### ISSUE TITLE
Javascript Object Conversion

### ISSUE THREAD

**Issue by shivanan** [JohnMasen/ChakraCore.NET#10]
I'm trying to write a converter to convert a native javascript object into an IDictionary<string,object>.

One issue I'm facing is how to recursively convert the values from .NET into their corresponding javascript type for the value entries in the dictionary.

I can't use `service.ToJSValue<T>` because I don't know what T will be - it will change at runtime.

One possible solution is to have an alternative `ToJSValue()` function which go through all registered converters and finds the first suitable one (basically checking the type of the parameter at runtime).

Is there any other easy solution that I'm missing?

If that solution sounds ok - I can do a PR for it.

**Comment by JohnMasen** [comment]
Hi,suggest see the array converter which implements IEnumeratble<T>. The key concept is this library always use strong type. As long as end user will register their own type, all they need to do is just another line like “registerDictionary<string,mytype>”. 

The API ToJsValue(value,type) was in the early version, I removed it because I found when your project is referenced by other project, and that project is also referenced by other project. It will be difficult to maintain a weak-type value converting system across these complex references. 

However, feel free to create your own converter library in your own namespace(just like I did for promise and arraybuffer value converter). And I’m open to discuss if we can find other solution for your requirement.

**Comment by DrEight** [comment]
Funny, I was posting the same question. I have to pass to js a Dictionary<string, object> and get back the same object modified.
Can you help guys to figure out how to do it? Any code/example would be appreciated. Thanks a lot

**Comment by JohnMasen** [comment]
No problem, I’ll create a sample of IDictionary. I’m currently on travel, will be back the day after tomorrow. Suggest you start think dictionary as Ienumeratble<dictionaryItem>, as that’s how I’m going to implement. As is does not have corresponding IDictionary interface, it will be implemented like IEnumeratable<dictionaryItem>.

**Comment by JohnMasen** [comment]
Correction: “as is does not ....” -> “as js does not ...”

**Comment by shivanan** [comment]
>However, feel free to create your own converter library in your own namespace(just like I did for promise and arraybuffer value converter). And I’m open to discuss if we can find other solution for your requirement.

Thanks for the feedback.

For this to work - it would be great to be able to query the list of already registered converters (I guess the `converters` SortedDictionary needs to be exposed in some way?).
This way when we see some value to be converted ,we can check if a converter already exists for that type and use that.

**Comment by JohnMasen** [comment]
I can expose TryGetConverter(type, out fromjs, out toJs) [return bool ] API in next version. 
However it is still suggested use generic instead of type query.

**Comment by JohnMasen** [comment]
Seems expose the TryGetConverter may impact the ServiceNode system, I can expose the CanConvert(type) instead.

to help better understanding how to use this library, I will a demo project now, please check the read.me file on main page for more details.

**Comment by JohnMasen** [comment]
CanConvert(type t) is now exposed in last checkin. nuget package will be updated later.

**Comment by JohnMasen** [comment]
hi, I created a samples repository at https://github.com/JohnMasen/Chakracore.NET-Samples

hope this can answer your question
