### ISSUE TITLE
Memory corruption

### ISSUE THREAD

**Issue by DrEight** [JohnMasen/ChakraCore.NET#17]
I have a problem of memory corruption passing a Task<T> to the rules.
The corruption happens in the file PromiseServiceInjector.cs in the line #106. When the ThreadPool is under stress the Task.Factory.StartNew spawn a new thread instead of using the current one. This is a document behavior of Task.Factory.StartNew. The result is that 2 threads handle the same code and chakra complains of a memory corruption. 
This does NOT happen in normal scenario.
Do you have any suggestion on how to fix this problem ?

**Comment by JohnMasen** [comment]
Thanks for your report. Could you send me a demo code for this issue?

**Comment by DrEight** [comment]
I sent you an email with more information

**Comment by JohnMasen** [comment]
Just did a quick review on your code, please try the following steps in your code.
1.define a global function<int> points to SetTimeOut
2. Use the delegate as parameter instead of SetTimeout method in binding.setmethod

**Comment by JohnMasen** [comment]
Func< int >

**Comment by JohnMasen** [comment]
SetTimeout is a build in function in chakracontext, you can see the code for a reference, it requires a bit additional implementation to handle the callback delegate.

**Comment by JohnMasen** [comment]
Just thought it again, this exception usually happens when js try to callback to c# but the entry point was disposed. Seems the “new MyTestProxy()” may cause this problem.

**Comment by DrEight** [comment]
I found the problem. Since I use ConcurrentBag to save a pool of contexts I notice that the callBack could take longer than the cycle to use the Context Pool. So it happens that a context that it is still waiting to return the callback is used by another thread.  So when the callback returns the context is executing a different rule. It is my fault, the library is OK!

I took a look to the implementation of setTimeOut. My thoughts are:
1) since many libraries use setTimeOut(..., 0), can we avoid to create a new task ( in some cases a new thread) to just wait 0ms ? It is a waste of resources. I think we can say: if( delay== ) callback();
2) Task.Factory.StartNew is an overhead. Here there is probably a better solution : https://blogs.msdn.microsoft.com/pfxteam/2012/03/24/should-i-expose-asynchronous-wrappers-for-synchronous-methods/

Since I keep the same runtime with a pool of contexts for the server lifetime, I notice that the performance of the rule execution decrease with the time. Do I have to garbage collect something ? Do you have any suggestion ?

I don't fully understand the context switch of the library, but to increase the performance can we avoid to switch if the managed thread is the same ? 


Thank you again for your time. I appreciate

**Comment by JohnMasen** [comment]
Glad to hear your problem is solved :)

1. You can implement your own setTimeOut. but suggest use the Promise as that's the official way and solves a lot of compatibility problems. the Chakracore.NET is trying to throw off these history problems to provide a better and clean implementation.

2. Agree with you, Task.FActory.StartNew is overhead. I'll put it in the feature list.

ideally javascript engine should keep same performance as it's single threaded. however it could cause memory leak if you add property to Global object without manually set it to null , any resource referenced by this property will also not be released. this may cause your callback function keeps awake.

chakracore uses "rental" thread model which requies "enter" and "leave". ideally you can simply Enter after a context is created and Leave before context is destroyed. however when you use Task or async, things becomes much more complicated. chakracore.net wrapps every single engine operation with "enter" and "leave" to make each call atomic to prevent any potencial cross thread conflict. as the target of this library is make it easy to use, I choose to sacrifise performance to provide an easy to use library. However, the framework is designed as "service-node oritend", you can replace/inject any core service by your own implementation without recompile the chakracore.net project.

Actully I found the traditional flow-oritend javascript is causing too many problems, that's why I recommand use the Hosting name space to load your javascript class as a C# class. I believe node.js is facing the same challenge, that's why Ryan is creating Deno instead of continue working on node.js :)

**Comment by DrEight** [comment]
You can close this issue. I fixed the bug in my code with your help
